---
title: "STAT 30030 Homework 2, Exercise 7: \n Rejection Sampling"
author: "Robert Winter"
format: pdf
highlight-style: pygments
geometry:
      - top=30mm
      - left=30mm
toc: true
toc-title: Table of Contents
number-sections: true
editor: visual

# Wrap code chunk text
include-in-header:
  text: |
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---

# Introduction

Implement rejection sampling to obtain 1,000 samples distributed with a Beta(2,2) distribution using samples from a $\mathcal{U}[0,1]$ distribution. Plot a histogram with your 1,000 samples and superimpose the density of a Beta(2,2) distribution.

# Analysis

```{r}
#| include: false
library(dplyr)
```

```{r}
# Obtain 2000 samples from the Unif[0, 1] distribution.
sample = data.frame(unif = runif(2000, 0, 1))

# Obtain 2000 samples from the Beta(2, 2) distribution based on our samples from the uniform distribution.
sample$betaDensity = dbeta(sample$unif, 2, 2)

# Set normalizing constant to be the maximum Beta density value
maxDens = max(sample$betaDensity, na.rm = T)

# Apply the acceptance / rejection criterion
sample$accepted = ifelse(runif(2000, 0, 1) < sample$betaDensity / maxDens, T, F)

# Filter down to the first 1000 samples accepted
sample <- sample %>%
  filter(accepted == T)
sample <- sample[c(1:1000),]
```

```{r}
# Plot histogram
hist(sample$unif[sample$accepted], freq = F, main = "Beta(2,2) Data Generated Using Rejection Sampling", xlab = "Accepted Draws from U[0,1]")

# Plot the Beta(2, 2) distribution
curve(dbeta(x, 2, 2), from = 0, to = 1, add = T)
```
